services:
  - type: web
    name: timesheet-drf-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && \
      python manage.py create_superuser_if_not_exists && \
      gunicorn timesheet_management_system.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'timesheet-drf-app.onrender.com'
      - key: CORS_ALLOWED_ORIGINS
        value: 'https://timesheetmgmt.netlify.app,http://localhost:3000'
