services:
  - type: web
    name: timesheet-drf-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn timesheet_management_system.wsgi:application
    postDeployCommand: |
      python manage.py migrate && \
      python manage.py create_superuser_if_not_exists
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'timesheet-management-dqe8.onrender.com'
