services:
  - type: web
    name: my-drf-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: 
      - python manage.py makemigrations
      - python manage.py migrate
      - gunicorn timesheet_management_system.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'timesheet-management-dqe8.onrender.com'
