services:
  - type: web
    name: my-drf-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myapp.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'timesheet.onrender.com'
