# Generated by Django 5.1.1 on 2024-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_customuser_otp_code_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin'), ('Manager', 'Manager')], default='Employee', max_length=10),
        ),
    ]
