# Generated by Django 5.1.1 on 2024-10-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timesheet.employee'),
        ),
    ]
